package org.cip4.lib.xjdf.xml;

import java.io.IOException;
import java.io.OutputStream;

import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.JAXBException;

import org.cip4.lib.xjdf.exception.XJdfParseException;
import org.cip4.lib.xjdf.schema.XJDF;
import org.cip4.lib.xjdf.xml.internal.AbstractXmlParser;
import org.cip4.lib.xjdf.xml.internal.AbstractXmlValidator;
import org.cip4.lib.xjdf.xml.internal.JAXBContextFactory;
import org.cip4.lib.xjdf.xml.internal.XJdfNamespaceMapper;
import org.glassfish.jaxb.runtime.marshaller.NamespacePrefixMapper;

/**
 * Parsing logic for building a XML Document from XJDF DOM-Tree and the way around.
 */
public class XJdfParser extends AbstractXmlParser<XJDF> {

    private final boolean enforceNamespacePrefix;

    private static JAXBContext getJAXBContextInstance() throws XJdfParseException {
        try {
            return JAXBContextFactory.getInstance();
        } catch (JAXBException e) {
            throw new XJdfParseException(e);
        }
    }

    /**
     * Default constructor.
     */
    public XJdfParser() throws XJdfParseException {
        this(true);
    }

    /**
     * Custom constructor. Accepting a flag for initializing.
     *
     * @param enforceNamespacePrefix True in case namespace prefix is requried.
     */
    public XJdfParser(boolean enforceNamespacePrefix) throws XJdfParseException {
        super(getJAXBContextInstance());
        this.enforceNamespacePrefix = enforceNamespacePrefix;
    }

    /**
     * Parse a XJDF Object Tree to a binary output stream.
     *
     * @param xJdf XJDF Object Tree for parsing.
     * @param os Target OutputStream where XJdfDocument is being parsed.
     */
    public final void parseXJdf(final XJDF xJdf, final OutputStream os)
        throws XJdfParseException {
        parseXJdf(xJdf, os, false);
    }

    /**
     * Parse a XJDF Object Tree to a binary output stream.
     *
     * @param xJdf XJDF Object Tree for parsing.
     * @param os Target OutputStream where XJdfDocument is being parsed.
     * @param skipValidation Skip validation.
     */
    public final void parseXJdf(final XJDF xJdf, final OutputStream os, final boolean skipValidation)
        throws XJdfParseException {
        parseXml(xJdf, os, skipValidation);
    }

    /**
     * Parse a XJDF Object Tree to a byte array.
     *
     * @param xJdf XJDF Object Tree for parsing.
     *
     * @return XJDF as byte array.
     * @throws IOException Is thrown in case any IO error occurs.
     * @throws JAXBException Is thrown in case any error while un-/marshalling occurs.
     */
    public final byte[] parseXJdf(final XJDF xJdf)
        throws XJdfParseException, IOException {

        return parseXml(xJdf, false);
    }

    /**
     * Parse a XJDF Object Tree to a byte array.
     *
     * @param xJdf XJDF Object Tree for parsing.
     * @param skipValidation Skip validation.
     *
     * @return XJDF as byte array.
     */
    public final byte[] parseXJdf(final XJDF xJdf, final boolean skipValidation)
        throws XJdfParseException, IOException {

        return parseXml(xJdf, skipValidation);
    }

    @Override
    protected final NamespacePrefixMapper getNamespacePrefixMapper() {
        return new XJdfNamespaceMapper(enforceNamespacePrefix);
    }

    @Override
    protected final String getXmlHeader() {
        String header = "<!-- Generated by CIP4 xJdfLib " + XJdfConstants.XJDFLIB_VERSION + " -->\r\n";
        header = header.replaceAll("  ", " ");
        return header;
    }

    @Override
    protected final AbstractXmlValidator createValidator() {
        return new XJdfValidator();
    }

}
