
package org.cip4.lib.xjdf.schema.jdf;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParameterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParameterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParameterType")
@XmlSeeAlso({
    GlueLine.class,
    DigitalDeliveryParams.class,
    DigitalPrintingParams.class,
    ShapeDefProductionParams.class,
    CasingInParams.class,
    HoleList.class,
    BarcodeReproParams.class,
    PreflightReportRulePool.class,
    TransferFunctionControl.class,
    RefAnchor.class,
    CoilBindingParams.class,
    LayoutElementProductionParams.class,
    DBRules.class,
    QualityControlResult.class,
    ShapeDef.class,
    CustomerInfo.class,
    AutomatedOverPrintParams.class,
    ApprovalParams.class,
    HeadBandApplicationParams.class,
    ProductionPath.class,
    ManualLaborParams.class,
    InsertingParams.class,
    HoleMakingParams.class,
    VarnishingParams.class,
    ShapeCuttingParams.class,
    PDLCreationParams.class,
    CylinderLayoutPreparationParams.class,
    CutBlock.class,
    VerificationParams.class,
    ProofingParams.class,
    DeviceNSpace.class,
    Contact.class,
    DensityMeasuringField.class,
    ComChannel.class,
    RunList.class,
    GlueApplication.class,
    DBSchema.class,
    Trigger.class,
    Hole.class,
    ThreadSealingParams.class,
    BendingParams.class,
    FontPolicy.class,
    DeviceMark.class,
    CutMark.class,
    RegisterMark.class,
    JobField.class,
    ColorControlStrip.class,
    CIELABMeasuringField.class,
    ScavengerArea.class,
    InsertSheet.class,
    TransferCurvePool.class,
    QualityControlParams.class,
    ElementColorParams.class,
    PreflightReport.class,
    ImageReplacementParams.class,
    CreasingParams.class,
    ImageSetterParams.class,
    GluingParams.class,
    DBSelection.class,
    InterpretingParams.class,
    PreflightParams.class,
    BlockPreparationParams.class,
    TransferCurve.class,
    LongitudinalRibbonOperationParams.class,
    Address.class,
    Fold.class,
    DieLayout.class,
    FontParams.class,
    ContactCopyParams.class,
    Color.class,
    NumberingParams.class,
    CylinderLayout.class,
    ByteMap.class,
    SaddleStitchingParams.class,
    ShrinkingParams.class,
    SpinePreparationParams.class,
    FitPolicy.class,
    ImageCompressionParams.class,
    EndSheetGluingParams.class,
    StrappingParams.class,
    ColorantAlias.class,
    DBMergeParams.class,
    Person.class,
    IdentificationField.class,
    PerforatingParams.class,
    FoldingParams.class,
    BinderySignature.class,
    PSToPDFConversionParams.class,
    InterpretedPDLData.class,
    Preview.class,
    AssetListCreationParams.class,
    LayoutPreparationParams.class,
    StripBindingParams.class,
    CoverApplicationParams.class,
    PlasticCombBindingParams.class,
    NodeInfo.class,
    RenderingParams.class,
    FoldOperation.class,
    FileSpec.class,
    ConventionalPrintingParams.class,
    PackingParams.class,
    Layout.class,
    CaseMakingParams.class,
    StackingParams.class,
    BarcodeCompParams.class,
    TrappingParams.class,
    PalletizingParams.class,
    JacketingParams.class,
    HoleLine.class,
    PlateCopyParams.class,
    WrappingParams.class,
    EmbossingParams.class,
    SeparationControlParams.class,
    ApprovalSuccess.class,
    PDFToPSConversionParams.class,
    ColorMeasurementConditions.class,
    ObjectResolution.class,
    InkZoneProfile.class,
    ThreadSewingParams.class,
    CuttingParams.class,
    CollectingParams.class,
    StitchingParams.class,
    ScreeningParams.class,
    LaminatingParams.class,
    PreviewGenerationParams.class,
    BufferParams.class,
    Company.class,
    InkZoneCalculationParams.class,
    AdhesiveBindingParams.class,
    DevelopingParams.class,
    SpineTapingParams.class,
    SideSewingParams.class,
    PageList.class,
    Assembly.class,
    Shape.class,
    MediaSource.class,
    TrapRegion.class,
    ChannelBindingParams.class,
    ContentList.class,
    GatheringParams.class,
    PreflightAnalysis.class,
    BundlingParams.class,
    DieLayoutProductionParams.class,
    DeliveryParams.class,
    FormatConversionParams.class,
    ResourceDefinitionParams.class,
    PrintRollingParams.class,
    PDLResourceAlias.class,
    PrintCondition.class,
    Tile.class,
    ColorCorrectionParams.class,
    ColorSpaceConversionParams.class,
    TrimmingParams.class,
    FeedingParams.class,
    ExternalImpositionTemplate.class,
    DividingParams.class,
    OrderingParams.class,
    RingBindingParams.class,
    PreflightInventory.class,
    LabelingParams.class,
    BoxPackingParams.class,
    StrippingParams.class,
    WireCombBindingParams.class,
    BoxFoldingParams.class,
    ColorantControl.class,
    LayoutShift.class,
    WebInlineFinishingParams.class,
    PreflightProfile.class,
    ScanParams.class,
    TrappingDetails.class
})
public class ParameterType implements Serializable
{


}
