# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
          
    - name: Decrypt GGP Ring File
      env:
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      run: gpg --quiet --batch --yes --decrypt --passphrase="$SIGNING_PASSWORD" --output secring.gpg secring.gpg.gpg
        
    - name: Build with Gradle
      run: ./gradlew check build jacocoTestReport
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: jar
        path: build/libs
        
    - name: Upload Archives to Sonatype
      run: ./gradlew uploadArchives 

